name: liferay-auto-upgrade
run-name: Liferay Auto Upgrade

on:
  push:
  # schedule:
  #   # https://crontab.guru/every-night-at-midnight
  #   - cron: '0 0 * * *'

jobs:
  liferay-upgrade:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: List remote branches
        run: |
          git ls-remote -q
          no_upgrade=$(git ls-remote -q | grep -q 'upgrade-to-dxp-74-u79' && echo false || echo true)
          echo $no_upgrade
      - name: Liferay Upgrade
        uses: lgdd/liferay-upgrade-action@main
        with:
          checkout: false
          java-distribution: 'zulu'
          java-version: '11'
          workspace-directory: './74-dxp-gradle-workspace'
