name: liferay-upgrade

on:
  push:
  # schedule:
  #   # https://crontab.guru/every-night-at-midnight
  #   - cron: '0 0 * * *'

jobs:
  upgrade-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Current Liferay Update
        working-directory: ./74-dxp-gradle-workspace
        run: |
          echo "LFR_CURRENT_PRODUCT_NAME=$(cat gradle.properties | grep liferay.workspace.product= | cut -d '=' -f2)" >> $GITHUB_ENV
      - name: Fetch Latest Liferay Update
        uses: actions/github-script@v6
        with:
          script: |
            const { LFR_CURRENT_PRODUCT_NAME } = process.env;
            console.log("LFR_CURRENT_PRODUCT_NAME=" + LFR_CURRENT_PRODUCT_NAME)
            const productSplit = LFR_CURRENT_PRODUCT_NAME.split('-');
            const currentEdition = productSplit[0]
            const currentVersion = productSplit[1].replaceAll('.', '')
            console.log("currentEdition=" + currentEdition);
            console.log("currentVersion=" + currentVersion);
            const liferayProductInfoUrl =
              `https://github.com/lgdd/liferay-product-info/raw/main/${currentEdition}_${currentVersion}_product_info.json`;

            fetch(liferayProductInfoUrl, { method: 'Get' })
              .then((res) => res.json())
              .then((json) => {
                const latestProduct = json[json.length - 1];
                console.log("LFR_LATEST_PRODUCT_NAME=" + latestProduct.name);
                core.exportVariable('LFR_LATEST_PRODUCT_NAME', latestProduct.name);
              });
      - uses: actions/checkout@v2
      - name: Set up JDK
        id: setup_jdk
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Cache Gradle packages
        id: cache_gradle_packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build Modules
        id: build_gradle
        run: |
          cd 74-dxp-gradle-workspace
          sed -i -e 's/${{ env.LFR_CURRENT_PRODUCT_NAME }}/${{ env.LFR_LATEST_PRODUCT_NAME }}/g' gradle.properties
          ./gradlew build
